### PR TITLE
Add django basic setup for projects

### PR DESCRIPTION
**Pull request by kurianbenoy**

### CODE REVIEW

**Comment by kurianbenoy** [comment]
Setup django and added details on how to install on README.md

**Comment by ashwin-nair98** [comment]
Add a gitignore file to remove cache and auto generated files

**Comment by guyandtheworld** [comment]
@slightlymadphoenix That's django default files right?

**Comment by kurianbenoy** [comment]
Yea this is just basic django files @slightlymadphoenix

**Comment by ashwin-nair98** [comment]
@isht3 @kurianbenoy 
Checkout the link below: 
https://www.gitignore.io/api/django

**Pull request merged**
